spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/to-do-list-app
  username: postgres
  password: postgres
 jpa:
  show-sql: true
  properties:
   hibernate:
    format_sql: true
    dialect: org.hibernate.dialect.PostgreSQLDialect
    enable_lazy_load_no_trans: true
  hibernate:
   ddl-auto: update
 application:
  name: liquibase demo
 liquibase:
  change-log: classpath:db.changelog/changelog-master.xml
  enabled: true